### ISSUE TITLE
Turkana DB detail view is broken

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore-retired#84]
Links to the detail view for specific records in the Turkana project returns a DoesNotExist error.

DoesNotExist at /projects/turkana/null/
Project matching query does not exist.
Request Method: GET
Request URL:    http://localhost:8000/projects/turkana/null/
Django Version: 1.6.5
Exception Type: DoesNotExist
Exception Value:  
Project matching query does not exist.
Exception Location: /usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/models/query.py in get, line 310
Python Executable:  /usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Python Version: 2.7.6
Python Path:  
['/Users/reedd/pycharm/paleocore',
 '/Library/Frameworks/SQLite3.framework/Versions/B/Python/2.7',
 '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7',
 '/Library/Python/2.7/site-packages/numpy-override',
 '/Library/Python/2.7/site-packages/matplotlib-override',
 '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages',
 '/Users/reedd/pycharm/paleocore',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages',
 '/Library/Python/2.7/site-packages']
Server time:    Fri, 3 Apr 2015 10:16:42 -0500

**Comment by wabarr** [comment]
should be fixed for now.  The problem was that the "id" field for Turkana wasn't being included in the list of fields to display in the paleocore_projects admin, and it must be.  I need to hardcode it in, but for now I just included it.

**Comment by dennereed** [comment]
OK let’s keep the issue open until we fix this right.

On April 3, 2015 at 12:33:59 PM, Andrew (notifications@github.com) wrote:

should be fixed for now. The problem was that the "id" field for Turkana wasn't being included in the list of fields to display in the paleocore_projects admin, and it must be. I need to hardcode it in, but for now I just included it.
